### ISSUE TITLE
Bugs to be fixed

### ISSUE THREAD

**Issue by jmirabel** [jmirabel/hpp-gui#11]
Here is a list of things that should be updated:

- [x] The `ConstraintWidget` / `NumericalConstraintPicker` is not very satisfactory. The list of numerical constraints (locked joint ?) should be taken from HPP,
- [x] `ConstraintWidget` never deletes `NumericalConstraintPicker`,
- [x] In the `BodyTree`, action should be applied to the selected items, not only to the current item,

**Comment by heidydallard** [comment]
The fix for the first two are solved on my devel branch.
I don't understand what you mean for the third one.
