### ISSUE TITLE
not compiling

### ISSUE THREAD

**Issue by olivier-stasse** [jmirabel/hpp-gui#3]
Dear Joseph,
Thanks for the GUI, 
I have however a compilation problem with:

/home/ostasse/devel/ros-indigo-1/src/hpp-gui/plugins/hppwidgetsplugin/solverwidget.cc:119:84: error: no matching function for call to ‘WorkItem_0<hpp::corbaserver::_objref_Problem, double>::WorkItem_0(_CORBA_ObjRef_Var<hpp::corbaserver::_objref_Problem, hpp::corbaserver::Problem_Helper>::T_ptr, hpp::intSeq* (hpp::corbaserver::_objref_Problem::*)())’
       (plugin_->client()->problem().in(), &hpp::corbaserver::_objref_Problem::solve);

I am using the master of hpp following the installation procedure given in the documentation.

**Comment by jmirabel** [comment]
Dear Olivier,

my fault, I did not update the master branch after the last HPP updates. It should be safe to use the devel branch.

**Comment by jmirabel** [comment]
It should be fixed now. Please try again and let me know.
Many thanks for your feedback.

**Comment by olivier-stasse** [comment]
Dear Joseph,
Apart some warnings due to type conversions your new update of the master is compiling without any problem.
Thanks for your quick answer.
